name: Build

on:
  push:
    branches:
      - main
    pull_request:
      - main
      - develop

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Build
      uses: actions/checkout@v3

    - run: xcodebuild -scheme PashaKit -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2'
